#ifndef CHARDEV_H
#define CHARDEV_H

#include <linux/ioctl.h>


#define MAJOR_NUM 237

#define READ_GYRO_X 1
#define READ_GYRO_Y 2
#define READ_GYRO_Z 3

#define READ_ACCELERO_X 4
#define READ_ACCELERO_Y 5
#define READ_ACCELERO_Z 6

#define READ_MAGNETO_X 7
#define READ_MAGNETO_Y 8
#define READ_MAGNETO_Z 9

#define READ_BARO 10

#define WRITE_FILE 11

#define IOCTL_READ_MSG_GYRO_X _IOR(MAJOR_NUM,READ_GYRO_X,int)
#define IOCTL_READ_MSG_GYRO_Y _IOR(MAJOR_NUM,READ_GYRO_Y,int)
#define IOCTL_READ_MSG_GYRO_Z _IOR(MAJOR_NUM,READ_GYRO_Z,int)


#define IOCTL_READ_MSG_ACCELERO_X _IOR(MAJOR_NUM,READ_ACCELERO_X,int)
#define IOCTL_READ_MSG_ACCELERO_Y _IOR(MAJOR_NUM,READ_ACCELERO_Y,int)
#define IOCTL_READ_MSG_ACCELERO_Z _IOR(MAJOR_NUM,READ_ACCELERO_Z,int)


#define IOCTL_READ_MSG_MAGNETO_X _IOR(MAJOR_NUM,READ_MAGNETO_X,int)
#define IOCTL_READ_MSG_MAGNETO_Y _IOR(MAJOR_NUM,READ_MAGNETO_Y,int)
#define IOCTL_READ_MSG_MAGNETO_Z _IOR(MAJOR_NUM,READ_MAGNETO_Z,int)


#define IOCTL_READ_MSG_BARO _IOR(MAJOR_NUM,READ_BARO,int)


#define IOCTL_WRITE_FILE _IOW(MAJOR_NUM,WRITE_FILE,unsigned long)

#define DEVICE_FILE_NAME "/dev/imu_char"

#endif

